### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by MrXyfir** [spinlud/redis-sliding-rate-limiter#1]
First off, thanks for this project! It's quite helpful.

I recently upgraded to v4 however and I couldn't find a changelog anywhere, which is especially important when there are breaking changes like in this version. A `CHANGELOG.md` file or documenting the changes in the Github releases would be amazing.

Thanks.

**Comment by spinlud** [comment]
Hi, thanks for the feeback.
There is no doubt a changelog will be useful, noted!

**Comment by spinlud** [comment]
Changelog added
